

prefixes = ["Mirai","mirai","-"]

#REACTIONS (reaction are exclusively available on the bot to avoid replication)
sorrygif = []
susgifs = []
bruhgifs = []
byegifs = []
cuddlegifs = []
gggifs = []
gmgifs = []
gngifs = []
hbdgifs = []
highfivegifs = []
huggif = []
kickgifs = []
lickgif = []
punchgifs = []
shootgifs = []
slapgifs = []
thankyougifs = []
vibegifs = []
wtfgifs = []
tiredgifs = []
confusedgifs = []
idkgifs = []
disgustgifs = []
hungrygifs = []
rollgifs = []
jkgifs = []
handshakesgifs = []
patgifs = []
killgifs = []
miraigifs = []
